fix npm backup issue #226
alichtman/shallow-backup pull request #315
Opened 2022-11-23 03:42 UTC by nick-The-One

This change solves issue #226 by using json format for dumping npm dependencies and parcing its keys — should be more robust than split by slash.

2023-03-05 18:02 UTC, nick-The-One commented
@alichtman Hey there! Could you take a look at this PR?

2023-03-06 00:39 UTC, alichtman requested changes
Hey, thanks for the ping + patience. [Insert _not enough time to do everything I want to do_ spiel].

I agree this PR is worthwhile. Thanks for taking the time to write it!

See the pointer to where changes are required for the reinstallation process. I'd love to have some automated end-to-end testing to make sure changes like this don't break anything.

Edit: Thought about it further; I'm not sure if any changes are required. Let me take another look when I get back to my computer. I wrote this code almost half a decade ago, and it's not super fresh in my mind anymore.

Edit 2: Yep, this seems to work as expected! Disregard v1 of my comments.

Cheers :)
Aaron

2023-03-06 00:39 UTC, alichtman commented on shallow_backup/backup.py
> +	temp_file_path = f"{backup_path}/npm_temp_list.json"
1. The filename change would need to be made in `reinstall.py`
2. The old reinstallation process would throw an error without some changes

Let's walk through it:

https://github.com/alichtman/shallow-backup/blob/b570f9d176a51878a97033915cab6b8216f48a12/shallow_backup/reinstall.py#L142-L145

Here's some example output from `$ npm ls --global --json=true --depth=0 > npm-json.txt`


```json
{
  "name": "lib",
  "dependencies": {
    "corepack": {
      "version": "0.15.3",
      "overridden": false
    },
    "insect": {
      "version": "5.8.0",
      "overridden": false
    },
    "md-to-pdf": {
      "version": "5.2.1",
      "overridden": false
    },
    "npm": {
      "version": "9.3.1",
      "overridden": false
    }
  }
}
```

```bash
$ cat npm-json.txt | xargs npm install -g
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "{" of package "{": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alichtman/.cache/npm/_logs/2023-03-06T00_26_49_097Z-debug-0.log
```

In order for this change to work, we'd need to parse out the modules *from* the `json` file we're creating (which is roughly what the logic that was removed from `backup.py` was doing).

2023-03-06 09:05 UTC, alichtman approved these changes

2023-03-06 09:06 UTC, merged